// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBPoK9X_Yhu9uW2QKXGdXnLUalSKTabSg',
    appId: '1:10698349196:web:cb97813805a5d06624b9a9',
    messagingSenderId: '10698349196',
    projectId: 'final-home-security',
    authDomain: 'final-home-security.firebaseapp.com',
    databaseURL: 'https://final-home-security-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'final-home-security.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHGlQ8oj6zuuMYw06s6qZlzJNZPXnW0cQ',
    appId: '1:10698349196:android:f5f2fcbc9adab47b24b9a9',
    messagingSenderId: '10698349196',
    projectId: 'final-home-security',
    databaseURL: 'https://final-home-security-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'final-home-security.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAu1GFm3D2y48isPM30LDhcE7CeBRUUp-E',
    appId: '1:10698349196:ios:036ff89b37a0a37124b9a9',
    messagingSenderId: '10698349196',
    projectId: 'final-home-security',
    databaseURL: 'https://final-home-security-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'final-home-security.appspot.com',
    iosBundleId: 'com.example.finalImranSalma',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAu1GFm3D2y48isPM30LDhcE7CeBRUUp-E',
    appId: '1:10698349196:ios:f7bc10f66f1c4c6d24b9a9',
    messagingSenderId: '10698349196',
    projectId: 'final-home-security',
    databaseURL: 'https://final-home-security-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'final-home-security.appspot.com',
    iosBundleId: 'com.example.finalImranSalma.RunnerTests',
  );
}
